ALTER TABLE resource_quotas ADD COLUMN IF NOT EXISTS priority VARCHAR(16) DEFAULT 'MEDIUM';
ALTER TABLE resource_quotas ADD COLUMN IF NOT EXISTS cpu_guaranteed DECIMAL(10,2) DEFAULT 0;
ALTER TABLE resource_quotas ADD COLUMN IF NOT EXISTS memory_guaranteed DECIMAL(10,2) DEFAULT 0;
ALTER TABLE resource_quotas ADD COLUMN IF NOT EXISTS gpu_guaranteed DECIMAL(10,2) DEFAULT 0;
ALTER TABLE resource_quotas ADD COLUMN IF NOT EXISTS preemption_policy VARCHAR(32) DEFAULT 'NONE';
ALTER TABLE resource_quotas ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'ACTIVE';
