apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform-core
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform-infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
